PROJ_NAME = tetris

SFML_DIR = ../SFML-2.5.1/

BUILD_DIR = build/

OBJ_DIR = obj

CPP_SOURCE = $(wildcard src/*.cpp)

H_SOURCE = $(wildcard headers/*.hpp)

OBJ = $(patsubst %.cpp, %.o, $(subst src, obj, $(CPP_SOURCE)))

T = $(subst *.cpp, *.o, $(OBJ))

CC = g++

CC_FLAGS =  -c -Wall

SFML = -lsfml-graphics -lsfml-system -lsfml-window -lsfml-audio 

INC = -I $(SFML_DIR)include -I headers/

LIB = -L $(SFML_DIR)lib

RM = del

all: obj $(PROJ_NAME)
run:
	E:\SFML_Projects\Tetris4ed\build\run.bat

$(PROJ_NAME): $(OBJ)
	@ echo 'Building binary using GPP linker : $@'
	@ $(CC) $^ $(SFML) $(INC) $(LIB) -o "$(BUILD_DIR)$@"
	@ echo 'Finished build binary: $@'

$(OBJ_DIR)/%.o: src/%.cpp headers/%.hpp
	@ echo '_____________________________________'
	@ echo 'Building target using GCC compiler: $<'
	@ $(CC) $< $(CC_FLAGS) $(INC) -o $@

obj/main.o: src/main.cpp 
	@ echo 'Building target using GCC compiler $<'
	@ $(CC) $< $(CC_FLAGS) $(INC) -o $@

obj:
	mkdir obj

clean:
	@ $(RM) obj\*.o
	@ rmdir obj

.PHONY: all clean
